### ISSUE TITLE
Add administrative users to useful groups by default.

### ISSUE THREAD

**Issue by rokejulianlockhart** [yast/yast-installation#1077]
My sole user for this machine is in none of the important groups by default. I've installed this to be used a personal machine, so this stuff should be configured automatically during intiial configuration by yast-installation.

This has meant that I am unable to invoke `flatpak remove` as my user. This prevents me removing them from plasma-discover either, which is a significant problem for a home user.

Instead, for simple administrative tasks, I must delegate them to the superuser. This a significant security and convenience flaw, which Fedora Workstation KDE Spin Rawhide does not share.

I've even had to manually add myself to wheel. That's why it is demonstrated as added in the screenshots:

![1](https://user-images.githubusercontent.com/42837531/214637526-8532af2f-5527-4b7e-a26a-2bc2b2747107.png)
![2](https://user-images.githubusercontent.com/42837531/214637474-f4c0dc52-95fc-455c-bcf4-39184b181f2b.png)

**Comment by shundhammer** [comment]
This is not really related to yast-installation.

**Comment by shundhammer** [comment]
I am not convinced that this would be a good default.

If you really want this, it's just a few clicks away:

- YaST control center
- Users

![user-01](https://user-images.githubusercontent.com/11538225/226633994-22611ccf-5984-462f-8a76-6b449e48e431.png)


- Edit (since you say you only have one user, that one is already selected)

![user-02](https://user-images.githubusercontent.com/11538225/226634054-1cd8463f-a317-4931-91f3-3e025069154b.png)

- Details

![user-03](https://user-images.githubusercontent.com/11538225/226634094-d37116d6-54d7-44aa-8030-537b41b1529d.png)

- Select as many groups as you like
- OK
- OK

**Comment by rokejulianlockhart** [comment]
Yeah, @shundhammer, but no new user will know to do that. Why would the default possibly prevent them using `flatpak`?

No other distribution has security policies like that. Those are the security policies I'd expect on RHEL or Windows Server (regarding `winget`) rather than Tumbleweed. At the very least, it's nonsensical *because* the user can still use `zypper` anyway, surely?

**Comment by shundhammer** [comment]
Also, what's wrong with using good old `sudo` for tasks that require root privileges? It allows fine-grained permissions to be delegated to users. And it will not give every security expert a fit.

**Comment by rokejulianlockhart** [comment]
I genuinely hadn't considered that that would work! If sudo was all that was needed, that makes a lot of sense.

**Comment by rokejulianlockhart** [comment]
Also, close as not planned rather than completed.
